### ISSUE TITLE
InlineValidationForm should be renamed

### ISSUE THREAD

**Issue by nerdoc** [iwanalabs/django-htmx-components#1]
https://github.com/iwanalabs/django-htmx-components/blob/3997260f0b9105d1aa9222513bcd78c73bbb69b2/src/components/inline_validation/forms.py#L58

This library is great. I just would make it more generic. This line is e.g. just a demo, and should be named something like DemoInlineValidationForm...

**Comment by dylanjcastillo** [comment]
Thank you @nerdoc.

Can you expand on that? Wouldn't `DemoInlineValidationForm` make it less generic?

**Comment by nerdoc** [comment]
Sure. The name "InlineValidationForm" suggests that it is a generic form for inline validation. Instead, it is a form that has a name, email, age and message field - for which you need a special use case. This is no way generic, just a demo for this exact purpose with 4  fields. It even has a fixed `form_url = reverse_lazy("form_inline_validation")`.

It would be much better to provide "generic" forms that can be subclassed - as "HtmxFormBase" does.

**Comment by dylanjcastillo** [comment]
I think what you mean now.

I've been thinking about this as more of a thing you copy-paste and customize to your needs. So kind of like [Tailwind UI](https://tailwindui.com/) for specific HTMX patterns.

It might be interesting to turn this into a set of components you could import into `django-components` and customize with a cleaner interface (e.g., subclassing and modifying some attributes), but I'd need to think more about the right approach for that + finding time

**Comment by nerdoc** [comment]
Completed as in merged or wontfix?

**Comment by dylanjcastillo** [comment]
Won’t fix for now. But I’ll keep it mind and might revisit it in the future.

**Comment by stuaxo** [comment]
> I think what you mean now.
> 
> I've been thinking about this as more of a thing you copy-paste and customize to your needs. So kind of like [Tailwind UI](https://tailwindui.com/) for specific HTMX patterns.
> 
> It might be interesting to turn this into a set of components you could import into `django-components` and customize with a cleaner interface (e.g., subclassing and modifying some attributes), but I'd need to think more about the right approach for that + finding time

This is definitely interesting.   

It would be good to include some examples that use more of Djangos form infrastructure to do the form rendering as well.

Maybe there would be FormComponent analagous to djangos FormView for instance.
