### ISSUE TITLE
Outside dev, it needs an example project

### ISSUE THREAD

**Issue by j2l** [iwanalabs/django-htmx-components#4]
I made it work by cloning and `make run`:
![image](https://github.com/iwanalabs/django-htmx-components/assets/65325/3f7b11af-fd9c-4f99-9e71-a174bf4481bf)

But I can't make it work with a django project from scratch. Readme is too succinct, I'm missing something.

Would you please make a minimal project using one (or many) of your components? 
(Without the side source code, just plain use)

**Comment by dylanjcastillo** [comment]
Hi @j2l,

Thank you for the feedback. I noticed you closed the issue now? Did you get it to work?

I'm planning to make it easier to install and work with later on.

Best,

**Comment by j2l** [comment]
Yes, it took me almost a day to split between the pure component from the demo and make it work in my setup.
I think an example project would be nice.

**Comment by dylanjcastillo** [comment]
Makes sense. Thank you.
